/*
  # Device Machine Tracking Setup

  1. New Tables
    - `device_machine`
      - `id` (bigint, primary key)
      - `created_at` (timestamp)
      - `MAC` (text)
      - `id_maquina` (bigint, foreign key)
      - `last_used` (timestamp)
      - `active` (boolean)

  2. Indexes
    - MAC address index for fast lookups
    - Composite index for MAC and active status

  3. Security
    - Enable RLS
    - Add policies for authenticated users
*/

-- Recreate table with additional columns
CREATE TABLE IF NOT EXISTS public.device_machine (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  "MAC" text NOT NULL,
  id_maquina bigint NOT NULL,
  last_used timestamp with time zone NOT NULL DEFAULT now(),
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT device_machine_pkey PRIMARY KEY (id),
  CONSTRAINT device_machine_id_maquina_fkey FOREIGN KEY (id_maquina) 
    REFERENCES "Maquinas" (id_maquina) ON DELETE CASCADE,
  CONSTRAINT device_machine_mac_unique UNIQUE ("MAC")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_device_machine_mac ON public.device_machine ("MAC");
CREATE INDEX IF NOT EXISTS idx_device_machine_mac_active ON public.device_machine ("MAC", active);

-- Enable Row Level Security
ALTER TABLE device_machine ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for authenticated users"
  ON public.device_machine
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Enable insert for authenticated users"
  ON public.device_machine
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users"
  ON public.device_machine
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);