/*
  # Add RLS policies for production history

  1. New Tables
    - `historico_producao`
      - `id` (bigint, primary key)
      - `created_at` (timestamptz)
      - `id_maquina` (bigint, foreign key)
      - `id_operador` (bigint, foreign key)
      - `id_semana_maquina` (bigint, foreign key)
      - `id_grade_semana_maquina` (bigint, foreign key)
      - `quantidade_produzida` (integer)
      - `quantidade_rejeitada` (integer)
      - `data_inicio` (timestamptz)
      - `data_fim` (timestamptz)
      - `status` (text)

  2. Security
    - Enable RLS on historico_producao table
    - Add policies for:
      - Authenticated users can read their own records
      - Operators can insert records
      - Operators can update their own records
      - Admins have full access
*/

-- Create the production history table
CREATE TABLE IF NOT EXISTS historico_producao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  id_maquina bigint REFERENCES "Maquinas"(id_maquina),
  id_operador bigint REFERENCES operador(id),
  id_semana_maquina bigint REFERENCES semana_maquina(id),
  id_grade_semana_maquina bigint REFERENCES grade_semana_maquina(id),
  quantidade_produzida integer DEFAULT 0,
  quantidade_rejeitada integer DEFAULT 0,
  data_inicio timestamptz,
  data_fim timestamptz,
  status text CHECK (status IN ('em_producao', 'finalizado', 'trocado'))
);

-- Enable Row Level Security
ALTER TABLE historico_producao ENABLE ROW LEVEL SECURITY;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_historico_producao_maquina 
ON historico_producao(id_maquina);

CREATE INDEX IF NOT EXISTS idx_historico_producao_operador 
ON historico_producao(id_operador);

CREATE INDEX IF NOT EXISTS idx_historico_producao_semana_maquina 
ON historico_producao(id_semana_maquina);

-- Policy for operators to read their own records
CREATE POLICY "Operators can read own records"
ON historico_producao
FOR SELECT
TO authenticated
USING (
  auth.uid() IN (
    SELECT user 
    FROM operador 
    WHERE id = historico_producao.id_operador
  )
);

-- Policy for operators to insert records
CREATE POLICY "Operators can insert records"
ON historico_producao
FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() IN (
    SELECT user 
    FROM operador 
    WHERE id = historico_producao.id_operador
  )
);

-- Policy for operators to update their own records
CREATE POLICY "Operators can update own records"
ON historico_producao
FOR UPDATE
TO authenticated
USING (
  auth.uid() IN (
    SELECT user 
    FROM operador 
    WHERE id = historico_producao.id_operador
  )
)
WITH CHECK (
  auth.uid() IN (
    SELECT user 
    FROM operador 
    WHERE id = historico_producao.id_operador
  )
);

-- Policy for admins to have full access
CREATE POLICY "Admins have full access"
ON historico_producao
TO authenticated
USING (
  auth.uid() IN (
    SELECT user 
    FROM operador 
    WHERE nivel = 'admin'
  )
)
WITH CHECK (
  auth.uid() IN (
    SELECT user 
    FROM operador 
    WHERE nivel = 'admin'
  )
);

-- Grant necessary privileges
GRANT ALL ON historico_producao TO authenticated;
GRANT USAGE ON SEQUENCE historico_producao_id_seq TO authenticated;