/*
  # Production History and Station Management

  1. New Tables
    - `producao_historico`: Tracks completed production runs
      - `id` (bigint, primary key)
      - `id_producao` (references producao_maquina_estacao)
      - `quantidade_produzida` (integer)
      - `quantidade_rejeitada` (integer)
      - `data_inicio` (timestamptz)
      - `data_fim` (timestamptz)
      - `id_operador` (bigint)
      
  2. Functions
    - `finish_production`: Handles production completion logic
      - Updates related tables
      - Creates history record
      - Updates balances
      
  3. Triggers
    - After production completion to update related records
*/

-- Create production history table
CREATE TABLE IF NOT EXISTS producao_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  id_producao bigint REFERENCES producao_maquina_estacao(id),
  quantidade_produzida integer NOT NULL DEFAULT 0,
  quantidade_rejeitada integer NOT NULL DEFAULT 0,
  data_inicio timestamptz NOT NULL,
  data_fim timestamptz NOT NULL,
  id_operador bigint REFERENCES operador(id),
  metadata jsonb
);

-- Function to handle production completion
CREATE OR REPLACE FUNCTION finish_production()
RETURNS trigger AS $$
BEGIN
  -- Update semana_maquina quantities
  UPDATE semana_maquina sm
  SET 
    quantidade_produzida = COALESCE(quantidade_produzida, 0) + NEW.quantidade_produzida,
    status = CASE 
      WHEN quantidade <= COALESCE(quantidade_produzida, 0) + NEW.quantidade_produzida 
      THEN 'concluido' 
      ELSE status 
    END
  FROM producao_maquina_estacao pme
  WHERE pme.id = NEW.id
  AND sm.id = pme.id_semana_maquina;

  -- Update grade_semana_maquina quantities
  UPDATE grade_semana_maquina gsm
  SET 
    quantidade_produzida = COALESCE(quantidade_produzida, 0) + NEW.quantidade_produzida,
    status = CASE 
      WHEN quantidade <= COALESCE(quantidade_produzida, 0) + NEW.quantidade_produzida 
      THEN 'concluido' 
      ELSE status 
    END
  FROM producao_maquina_estacao pme
  WHERE pme.id = NEW.id
  AND gsm.id = pme.id_grade_semana_maquina;

  -- Create history record
  INSERT INTO producao_historico (
    id_producao,
    quantidade_produzida,
    quantidade_rejeitada,
    data_inicio,
    data_fim,
    id_operador
  )
  VALUES (
    NEW.id,
    NEW.quantidade_produzida,
    NEW.quantidade_rejeitada,
    NEW.data_inicio,
    NEW.data_fim,
    NEW.id_operador
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for production completion
CREATE TRIGGER after_production_completion
  AFTER UPDATE OF status ON producao_maquina_estacao
  FOR EACH ROW
  WHEN (NEW.status = 'finalizado')
  EXECUTE FUNCTION finish_production();