/*
  # Production Tracking System Enhancement

  1. New Tables
    - `producao_maquina_estacao`: Links stations to productions
    - `producao_maquina_matriz`: Tracks matrix usage per station

  2. Changes
    - Add new columns to machine_parameters
    - Add relationships between tables
    - Enable RLS on new tables

  3. Security
    - Add policies for authenticated users
    - Ensure proper access control
*/

-- Add new columns to machine_parameters
ALTER TABLE machine_parameters
ADD COLUMN IF NOT EXISTS producao_ativa boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS estacoes jsonb DEFAULT '[]'::jsonb;

-- Create station production tracking table
CREATE TABLE IF NOT EXISTS public.producao_maquina_estacao (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id_maquina bigint NOT NULL,
  numero_estacao integer NOT NULL,
  id_semana_maquina bigint NOT NULL,
  id_grade_semana_maquina bigint NOT NULL,
  status text NOT NULL DEFAULT 'em_producao',
  quantidade_produzida integer DEFAULT 0,
  quantidade_rejeitada integer DEFAULT 0,
  CONSTRAINT producao_maquina_estacao_pkey PRIMARY KEY (id),
  CONSTRAINT producao_maquina_estacao_maquina_fkey FOREIGN KEY (id_maquina) 
    REFERENCES "Maquinas" (id_maquina) ON DELETE CASCADE,
  CONSTRAINT producao_maquina_estacao_semana_fkey FOREIGN KEY (id_semana_maquina) 
    REFERENCES semana_maquina (id) ON DELETE CASCADE,
  CONSTRAINT producao_maquina_estacao_grade_fkey FOREIGN KEY (id_grade_semana_maquina) 
    REFERENCES grade_semana_maquina (id) ON DELETE CASCADE,
  CONSTRAINT producao_maquina_estacao_status_check 
    CHECK (status IN ('pendente', 'em_producao', 'pausado', 'finalizado')),
  CONSTRAINT producao_maquina_estacao_unique 
    UNIQUE (id_maquina, numero_estacao)
);

-- Create matrix usage tracking table
CREATE TABLE IF NOT EXISTS public.producao_maquina_matriz (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id_producao_estacao bigint NOT NULL,
  id_matriz bigint NOT NULL,
  data_inicio timestamp with time zone NOT NULL DEFAULT now(),
  data_fim timestamp with time zone,
  CONSTRAINT producao_maquina_matriz_pkey PRIMARY KEY (id),
  CONSTRAINT producao_maquina_matriz_producao_fkey FOREIGN KEY (id_producao_estacao) 
    REFERENCES producao_maquina_estacao (id) ON DELETE CASCADE,
  CONSTRAINT producao_maquina_matriz_matriz_fkey FOREIGN KEY (id_matriz) 
    REFERENCES matrizes (id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE producao_maquina_estacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE producao_maquina_matriz ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for authenticated users on producao_maquina_estacao"
  ON producao_maquina_estacao
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Enable insert/update for authenticated users on producao_maquina_estacao"
  ON producao_maquina_estacao
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable read access for authenticated users on producao_maquina_matriz"
  ON producao_maquina_matriz
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Enable insert/update for authenticated users on producao_maquina_matriz"
  ON producao_maquina_matriz
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_producao_maquina_estacao_maquina 
  ON producao_maquina_estacao (id_maquina);
CREATE INDEX IF NOT EXISTS idx_producao_maquina_estacao_status 
  ON producao_maquina_estacao (status);
CREATE INDEX IF NOT EXISTS idx_producao_maquina_matriz_producao 
  ON producao_maquina_matriz (id_producao_estacao);