/*
  # Device tracking and operator sessions

  1. New Tables
    - `device_maquina_operador`: Tracks device MAC addresses and their associated machines/operators
      - `id` (bigint, primary key)
      - `mac_address` (text, unique with id_empresa)
      - `id_maquina` (bigint, references Maquinas)
      - `id_operador` (bigint, references operador)
      - `id_empresa` (bigint, references empresa)
      - `created_at` (timestamp)
      - `last_used` (timestamp)
      - `ativo` (boolean)

  2. Security
    - Enable RLS on new table
    - Add policies for authenticated users
*/

-- Device tracking table
CREATE TABLE IF NOT EXISTS public.device_maquina_operador (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mac_address text NOT NULL,
  id_maquina bigint NOT NULL,
  id_operador bigint NOT NULL,
  id_empresa bigint NOT NULL,
  last_used timestamp with time zone NOT NULL DEFAULT now(),
  ativo boolean NOT NULL DEFAULT true,
  CONSTRAINT device_maquina_operador_pkey PRIMARY KEY (id),
  CONSTRAINT device_maquina_operador_maquina_fkey FOREIGN KEY (id_maquina) REFERENCES "Maquinas" (id_maquina),
  CONSTRAINT device_maquina_operador_operador_fkey FOREIGN KEY (id_operador) REFERENCES operador (id),
  CONSTRAINT device_maquina_operador_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES empresa (id),
  CONSTRAINT device_maquina_operador_mac_empresa_unique UNIQUE (mac_address, id_empresa)
);

-- Enable RLS
ALTER TABLE device_maquina_operador ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow read access for authenticated users on device_maquina_operador"
  ON device_maquina_operador
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow insert/update for operators on device_maquina_operador"
  ON device_maquina_operador
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM operador WHERE user = auth.uid() AND id = id_operador
    )
  );

-- Function to handle operator session activation
CREATE OR REPLACE FUNCTION handle_operator_session_activation()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT' AND NEW.ativa = true) OR
     (TG_OP = 'UPDATE' AND NEW.ativa = true AND OLD.ativa = false) THEN
    -- Deactivate other active sessions for the same operator and machine
    UPDATE operador_sessoes
    SET ativa = false,
        data_saida = EXTRACT(EPOCH FROM NOW())
    WHERE id_operador = NEW.id_operador
      AND id_maquina = NEW.id_maquina
      AND id != NEW.id
      AND ativa = true;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;