/*
  # Add shifts table and functionality

  1. New Tables
    - `turnos` table for managing machine shifts
      - `id` (bigint, primary key)
      - `id_maquina` (bigint, foreign key to Maquinas)
      - `id_empresa` (bigint, foreign key to empresa)
      - `hora_inicio` (time without time zone)
      - `hora_fim` (time without time zone)
      - `descricao` (text)
      - `hora_inicio_txt` (text)
      - `hora_fim_txt` (text)
      - `dias_semana` (jsonb)

  2. Triggers
    - After insert/update trigger to update machine shifts
*/

CREATE TABLE IF NOT EXISTS public.turnos (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_maquina bigint NOT NULL,
  id_empresa bigint NOT NULL,
  hora_inicio time without time zone NOT NULL,
  hora_fim time without time zone NOT NULL,
  descricao text NULL,
  hora_inicio_txt text NULL,
  hora_fim_txt text NULL,
  dias_semana jsonb NULL,
  CONSTRAINT turnos_pkey PRIMARY KEY (id),
  CONSTRAINT turnos_id_empresa_fkey FOREIGN KEY (id_empresa) REFERENCES empresa (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT turnos_id_maquina_fkey FOREIGN KEY (id_maquina) REFERENCES "Maquinas" (id_maquina) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE turnos ENABLE ROW LEVEL SECURITY;

-- Add RLS policies
CREATE POLICY "Allow read access for authenticated users"
  ON turnos
  FOR SELECT
  TO authenticated
  USING (true);

-- Create trigger function
CREATE OR REPLACE FUNCTION update_machine_turnos()
RETURNS TRIGGER AS $$
BEGIN
  -- Add your trigger logic here if needed
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
CREATE TRIGGER after_insert_update_turnos
  AFTER INSERT OR UPDATE ON turnos
  FOR EACH ROW
  EXECUTE FUNCTION update_machine_turnos();