/*
  # Create workflow tables for production tracking

  1. New Tables
    - `producao_maquina`
      - Tracks active production on machines
      - Links to semana_maquina and grade_semana_maquina
      - Records start/end times and quantities
    - `producao_maquina_log`
      - Logs all production events
      - Records quantities, rejects, and timestamps
    - `producao_maquina_rejeitos`
      - Tracks rejected items with reasons
      - Links to production logs

  2. Security
    - Enable RLS on all tables
    - Add policies for authenticated users
*/

-- Production tracking table
CREATE TABLE IF NOT EXISTS public.producao_maquina (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id_semana_maquina bigint NOT NULL,
  id_grade_semana_maquina bigint NOT NULL,
  id_maquina bigint NOT NULL,
  id_operador bigint NOT NULL,
  data_inicio timestamp with time zone NOT NULL DEFAULT now(),
  data_fim timestamp with time zone NULL,
  quantidade_produzida integer DEFAULT 0,
  status text NOT NULL DEFAULT 'em_andamento',
  CONSTRAINT producao_maquina_pkey PRIMARY KEY (id),
  CONSTRAINT producao_maquina_semana_fkey FOREIGN KEY (id_semana_maquina) REFERENCES semana_maquina(id),
  CONSTRAINT producao_maquina_grade_fkey FOREIGN KEY (id_grade_semana_maquina) REFERENCES grade_semana_maquina(id),
  CONSTRAINT producao_maquina_maquina_fkey FOREIGN KEY (id_maquina) REFERENCES "Maquinas"(id_maquina),
  CONSTRAINT producao_maquina_operador_fkey FOREIGN KEY (id_operador) REFERENCES operador(id),
  CONSTRAINT producao_maquina_status_check CHECK (status IN ('em_andamento', 'pausado', 'finalizado'))
);

-- Production log table
CREATE TABLE IF NOT EXISTS public.producao_maquina_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id_producao_maquina bigint NOT NULL,
  quantidade integer NOT NULL DEFAULT 0,
  rejeitos integer NOT NULL DEFAULT 0,
  observacao text NULL,
  CONSTRAINT producao_maquina_log_pkey PRIMARY KEY (id),
  CONSTRAINT producao_maquina_log_producao_fkey FOREIGN KEY (id_producao_maquina) REFERENCES producao_maquina(id)
);

-- Rejects tracking table
CREATE TABLE IF NOT EXISTS public.producao_maquina_rejeitos (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id_producao_maquina_log bigint NOT NULL,
  quantidade integer NOT NULL DEFAULT 0,
  motivo text NOT NULL,
  observacao text NULL,
  CONSTRAINT producao_maquina_rejeitos_pkey PRIMARY KEY (id),
  CONSTRAINT producao_maquina_rejeitos_log_fkey FOREIGN KEY (id_producao_maquina_log) REFERENCES producao_maquina_log(id)
);

-- Enable RLS
ALTER TABLE producao_maquina ENABLE ROW LEVEL SECURITY;
ALTER TABLE producao_maquina_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE producao_maquina_rejeitos ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow read access for authenticated users on producao_maquina"
  ON producao_maquina
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow read access for authenticated users on producao_maquina_log"
  ON producao_maquina_log
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow read access for authenticated users on producao_maquina_rejeitos"
  ON producao_maquina_rejeitos
  FOR SELECT
  TO authenticated
  USING (true);

-- Insert policies for operators
CREATE POLICY "Allow insert/update for operators on producao_maquina"
  ON producao_maquina
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM operador WHERE user = auth.uid() AND id = id_operador
    )
  );

CREATE POLICY "Allow insert/update for operators on producao_maquina_log"
  ON producao_maquina_log
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 
      FROM producao_maquina pm 
      JOIN operador o ON o.id = pm.id_operador 
      WHERE pm.id = producao_maquina_log.id_producao_maquina 
      AND o.user = auth.uid()
    )
  );

CREATE POLICY "Allow insert/update for operators on producao_maquina_rejeitos"
  ON producao_maquina_rejeitos
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 
      FROM producao_maquina_log pml
      JOIN producao_maquina pm ON pm.id = pml.id_producao_maquina
      JOIN operador o ON o.id = pm.id_operador 
      WHERE pml.id = producao_maquina_rejeitos.id_producao_maquina_log
      AND o.user = auth.uid()
    )
  );