/*
  # Create matrizes table and update grade display

  1. New Tables
    - `matrizes`
      - `id` (bigint, primary key)
      - `identificador` (text)
      - `produto` (bigint, foreign key to produto)
      - `tamanho` (text)
      - `id_empresa` (bigint)
      - `maquina_atual` (bigint, foreign key to Maquinas)

  2. Security
    - Enable RLS on `matrizes` table
    - Add policy for authenticated users to read data
*/

CREATE TABLE IF NOT EXISTS public.matrizes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  identificador text NULL,
  produto bigint NULL,
  tamanho text NULL,
  id_empresa bigint NULL,
  maquina_atual bigint NULL,
  CONSTRAINT matrizes_pkey PRIMARY KEY (id),
  CONSTRAINT matrizes_maquina_atual_fkey FOREIGN KEY (maquina_atual) REFERENCES "Maquinas" (id_maquina),
  CONSTRAINT matrizes_produto_fkey FOREIGN KEY (produto) REFERENCES produto (id)
);

ALTER TABLE matrizes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users"
  ON matrizes
  FOR SELECT
  TO authenticated
  USING (true);