/*
  # Create Sessions and Machine Parameters Tables

  1. New Tables
    - `sessoes`: Tracks operator sessions
      - `id` (bigint, primary key)
      - `maquina` (bigint, foreign key to Maquinas)
      - `operador` (bigint, foreign key to operador)
      - `inicio` (bigint)
      - `fim` (bigint)
      - `turno` (bigint, foreign key to turnos)

    - `machine_parameters`: Tracks machine state
      - `id_maquina` (bigint, primary key)
      - `operador` (bigint, foreign key to operador)
      - `sessao` (bigint, foreign key to sessoes)
      - `produto` (bigint, foreign key to produto)
      - `semana_maquina` (bigint, foreign key to semana_maquina)
      - `grade_semana_maquina` (bigint, foreign key to grade_semana_maquina)

  2. Security
    - Enable RLS on both tables
    - Add policies for authenticated users
*/

-- Create sessions table
CREATE TABLE IF NOT EXISTS public.sessoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  maquina bigint NULL,
  operador bigint NULL,
  inicio bigint NULL,
  fim bigint NULL,
  turno bigint NULL,
  CONSTRAINT sessoes_pkey PRIMARY KEY (id),
  CONSTRAINT sessoes_maquina_fkey FOREIGN KEY (maquina) REFERENCES "Maquinas" (id_maquina),
  CONSTRAINT sessoes_operador_fkey FOREIGN KEY (operador) REFERENCES operador (id),
  CONSTRAINT sessoes_turno_fkey FOREIGN KEY (turno) REFERENCES turnos (id)
) TABLESPACE pg_default;

-- Create machine parameters table
CREATE TABLE IF NOT EXISTS public.machine_parameters (
  id_maquina bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  operador bigint NULL,
  sessao bigint NULL,
  produto bigint NULL,
  semana_maquina bigint NULL,
  grade_semana_maquina bigint NULL,
  CONSTRAINT machine_parameters_pkey PRIMARY KEY (id_maquina),
  CONSTRAINT machine_parameters_id_maquina_fkey FOREIGN KEY (id_maquina) REFERENCES "Maquinas" (id_maquina),
  CONSTRAINT machine_parameters_operador_fkey FOREIGN KEY (operador) REFERENCES operador (id),
  CONSTRAINT machine_parameters_produto_fkey FOREIGN KEY (produto) REFERENCES produto (id),
  CONSTRAINT machine_parameters_semana_maquina_fkey FOREIGN KEY (semana_maquina) REFERENCES semana_maquina (id),
  CONSTRAINT machine_parameters_grade_semana_maquina_fkey FOREIGN KEY (grade_semana_maquina) REFERENCES grade_semana_maquina (id),
  CONSTRAINT machine_parameters_sessao_fkey FOREIGN KEY (sessao) REFERENCES sessoes (id)
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE sessoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE machine_parameters ENABLE ROW LEVEL SECURITY;

-- Create policies for sessoes
CREATE POLICY "Allow read access for authenticated users on sessoes"
  ON sessoes
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow insert/update for authenticated users on sessoes"
  ON sessoes
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Create policies for machine_parameters
CREATE POLICY "Allow read access for authenticated users on machine_parameters"
  ON machine_parameters
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow insert/update for authenticated users on machine_parameters"
  ON machine_parameters
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);